### ISSUE TITLE
Some bugs connected with flyway

### ISSUE THREAD

**Issue by t-r-student** [kristinagerdt/Budget#28]
Set the version of flyway cause it's not working on Linux OS; 
All characters of table names in queries should be written in uppercase;
There is a some bug connected with foreign key constraint especially on Linux OS. Creation of transaction is not possible. It throws java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails(SQL Error: 1216, SQLState: 23000).

**Comment by sergeylukichev** [comment]
@kristinagerdt do you experience bugs you mention in the issue when starting the project?
